---
#apiVersion: v1
#data:
#  MYSQL_ROOT_PASSWORD: cm9vNjA2NDE=
#kind: Secret
#metadata:
#  name: mysql-secret
#type: Opaque
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs
  labels:
    app: mysql-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-rs
  template:
    metadata:
      labels:
        app: mysql-rs
    spec:
      containers:
      - name: mysql-cont
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootpasswd
        - name: MYSQL_DATABASE
          value: wordpress
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql
        persistentVolumeClaim:
          claimName: mysql-pvc
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-rs
  name: svc-mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-rs
  clusterIP: None
---
